### ISSUE TITLE
Error opening document

### ISSUE THREAD

**Issue by timchunght** [sharelatex/sharelatex-docker-image#46] opened 2016-05-04 17:28 UTC
I did all the setup correctly and mongo migration is working and redis is also connected. However, I still got this error when trying to open an document,

```
Error opening document
Sorry, something went wrong opening this document. Please try again.
```

Is there a way to debug this or has anyone seen this who has a solution? Thanks.

**Comment by ghost** [comment] 2016-05-20 14:44
same here

**Comment by metal3d** [comment] 2017-01-18 01:09
Same here... on openshift - seems that tex files are not created

**Comment by metal3d** [comment] 2017-01-18 01:10
@henryoswald can you explain why you closed that issue ?

**Comment by henryoswald** [comment] 2017-01-20 11:38
I am not familiar with openshift so can't really say what is wrong sorry.

**Comment by metal3d** [comment] 2017-01-23 23:42
The problem is not from openshift, but because used mongodb image needs strict authentication. With the "standard" mongo image from docker-hub there is no problem.

See #65 issue I've opened.

**Comment by ma-karai** [comment] 2017-04-13 16:00
I had this document viewer issue on every  version except the 0.6.1/latest one which seems to be working fine. (updated 3days ago) 

Except, spellchecking an the track changes won't work which gives an internal server error, so I assume someone needs to take a look at the docker internal nginx. conf and sharelatex. Conf

**Comment by ma-karai** [comment] 2017-04-20 07:31
Actually i narrowed it down, it is indeed the mongoDB authetication as soon as the mongodb needs an username and password some of the functionality breaks.

In the recent version 0.6.1 the document viewer works fine, however spellcheck and history alongside real-time does not work as long as mongoDB needs authentication.

**Comment by mserranom** [comment] 2020-02-26 15:25
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!

**Closed as completed by mserranom** 2020-02-26 15:25 UTC
